### ISSUE TITLE
Add a Search icon

### ISSUE THREAD

**Issue by djedi** [djedi/DailyNotes#45] opened 2021-11-23 22:02 UTC
It took me a while to find all the features in the screenshots. :) I think a search icon would be helpful. If you don't have any tags to click on, I'm not sure how you would even get to search. Its kind of a mystery navigation as it is.

**Comment by m0ngr31** [comment] 2021-11-24 01:31
Duplicate of #43

**Closed as completed by m0ngr31** 2021-11-24 01:31 UTC
